server:
  port: 8083
spring:
  application:
    name: ai-service
  mongodb:
    uri: mongodb+srv://atif276ali_db_user:az2YXYCoAEQlXnRa@cluster0.uzh9sxl.mongodb.net/pulse-ai
  rabbitmq:
    addresses: amqps://wzkkdora:GrjhpV0os5Sx9sijMRr10l4bL51iNRLi@puffin.rmq2.cloudamqp.com/wzkkdora

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    key: AIzaSyAI5XT3uP7Xu9pDsvRr9wgPbgG5NCkomqc