spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgres://localhost:5432/fitness_user_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect